### ISSUE TITLE
Add support for PHP 8

### ISSUE THREAD

**Issue by sumitramanga** [magenizr/Magenizr_Raygun#1]
Hi there!

Thank you so much for your contribution towards Raygun via this awesome module!

We recently got a request for support with PHP 8 for the Magento 2 module. 

Would this be something that can be added on your end? How quick would it be or will it take some time?

Kind regards,
Sumitra

**Comment by magenizr** [comment]
Hi @sumitramanga 

Thank you for reaching out! We didn't see any issues recently with PHP 8.x - but happy to review this again on the latest Magento version + PHP 8.1.

We'll come back with an update in the next 24 hrs.

Regards,
John

**Comment by sumitramanga** [comment]
Thank you so much @magenizr ! Looking forward to your update 🌟

**Comment by magenizr** [comment]
Hi @sumitramanga 

We'll provide an updated version this week, but can already confirm that the installation and backend configuration is working as it is on the latest Magento version.

![New Project - 2024-05-29T160115 220](https://github.com/magenizr/Magenizr_Raygun/assets/36174840/891484c6-b35b-4cbb-9a15-a9b4a7e98f0f)

```
www-data@247-php-fpm:/var/www/html$ composer install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 2 installs, 0 updates, 0 removals
  - Installing mindscape/raygun4php (v2.3.3): Extracting archive
  - Installing magenizr/magento2-raygun (1.0.0): Extracting archive
Package sebastian/phpcpd is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
148 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```
```
www-data@247-php-fpm:/var/www/html$ php -v
PHP 8.2.19 (cli) (built: May  7 2024 14:19:14) (NTS gcc aarch64)
Copyright (c) The PHP Group
Zend Engine v4.2.19, Copyright (c) Zend Technologies
    with the ionCube PHP Loader v13.0.3, Copyright (c) 2002-2024, by ionCube Ltd.
    with Zend OPcache v8.2.19, Copyright (c), by Zend Technologies
```
```
www-data@247-php-fpm:/var/www/html$ php bin/magento -V
Magento CLI 2.4.7
```

We're not done with testing, but if you received a specific issue from a customer, can you please share it here or email to support@magenizr.com.au?

Thank you,
John

**Comment by sumitramanga** [comment]
Hi @magenizr 

Thank you for the update and information. I'll let you know if the customer comes across any issue during the set up process or they will post here. 

I look forward to your further progress! 

Thank you again for all the efforts on this,

Cheers,
Sumitra

**Comment by sumitramanga** [comment]
Hi @magenizr We've also extended your trial period as we noticed you popping over to our app. Do let us know if you require more time and we can extend :)

**Comment by magenizr** [comment]
Hi @sumitramanga 

We completed a full test on Magento 2.4.7 and PHP 8.2 this morning and couldn't find any major issues. However, we ended up with a new release ( version 1.1.0 ) that includes minor updates which is available now.

Real User Monitoring:

![New Project - 2024-05-30T092020 208](https://github.com/magenizr/Magenizr_Raygun/assets/36174840/2e6c4bd6-4446-4b73-9ab7-7ffc1d88f219)

Crash Reporting:

![New Project - 2024-05-30T110711 912](https://github.com/magenizr/Magenizr_Raygun/assets/36174840/7df3c8cc-f63e-477a-84fa-d0b34c51ee4d)

Uninstall previous version:

```
composer remove "magenizr/magento2-raygun" --no-update
composer update magenizr/magento2-raygun --no-install

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 0 updates, 2 removals
  - Removing magenizr/magento2-raygun (1.0.0)
  - Removing mindscape/raygun4php (v2.3.3)
Writing lock file
```

Install new version:

```
composer require "magenizr/magento2-raygun":"^1.1.0" --no-update
composer update magenizr/magento2-raygun --no-install
composer install
```

If your client has still problems setting up Raygun properly, we can help directly with our Raygun Bundle:

- Enable Raygun in Magento
- Raygun Configuration and Training
- Set-up Crash Reporting and Real User Monitoring
- Set-up Standard and Individual Raygun Alerts
- 7 days Support * ( if needed )

Regards,
John

**Comment by sumitramanga** [comment]
Hi @magenizr 

This is amazing 🤩 Thank you so much for your additional support and taking the time to validate the results. I'll pass this onto the customer and will you know how they get on (we have passed on this thread already so that they can directly chat with you)

Kind regards,
Sumitra
