### ISSUE TITLE
Add this module documentation to the raygun.com/docs site

### ISSUE THREAD

**Issue by sumitramanga** [magenizr/Magenizr_Raygun#2]
Hi there,

I'd love to add this to the raygun.com/docs site! Just posting here for visibility that I'll be starting on this and if it's ok to use your content. I also may have some questions regarding your documentation to clarify 

Kind regards,
Sumitra

**Comment by magenizr** [comment]
Hi @sumitramanga 

These are great news! Feel free to copy/paste content from our Github page ( incl. screenshots ) For more information, we can share content via support@magenizr.com.au.

Regards,
John

**Comment by sumitramanga** [comment]
This has now been added to our public docs and I've also gone ahead and added installation steps to our onboarding area in the app when someone signed up and wants to set up the module! Gonna close this issue now (But I'd love to add in more suggestions as separate issues :-) )
