### ISSUE TITLE
Enable Crash Reporting and Real User Monitoring by default for faster installation/set up

### ISSUE THREAD

**Issue by sumitramanga** [magenizr/Magenizr_Raygun#3]
It is safe to say that if the API Key is added, then they are intending to set up Raygun's features

**Comment by magenizr** [comment]
Hi @sumitramanga 

Good point! We'll change that in the next version so that both features are enabled by default and only require the API key to be available.

**Comment by sumitramanga** [comment]
Hi @magenizr, Just wanted to check to see how this is going and if there'll be a release soon? 
Looking forward to your response!

**Comment by magenizr** [comment]
Hi @sumitramanga 

Yep, both will be enabled by default in the next version and will only require the API key to be present. The new release will be published tonight.

Regards,
John

**Comment by magenizr** [comment]
Release 1.1.1 has been published, thank you for your contribution 👍
