### ISSUE TITLE
Fix PHP label not rendering 🤔

### ISSUE THREAD

**Issue by sumitramanga** [magenizr/Magenizr_Raygun#6]
Just referencing the line number I think it's on - https://github.com/magenizr/Magenizr_Raygun/blob/16c08bd771c2b414e4341307ecf7c4808ec9babe/README.md?plain=1#L9

**Comment by magenizr** [comment]
Hi @sumitramanga 

We have updated the composer file but it doesn't update the PHP requirements for some reason. We'll have a look at it again.

John

**Comment by magenizr** [comment]
The PHP requirement " badge " has been updated in the README.md. Closing ticket
